sudo: required

services:
  - docker

before_install:
  - docker build -t sanikere/docker-react -f Dockerfile.dev .

script:
  - docker run sanikere/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-707129398531"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

